use script in oss

diff --git a/.github/workflows/exp-cross-build.yml b/.github/workflows/exp-cross-build.yml
--- a/.github/workflows/exp-cross-build.yml
+++ b/.github/workflows/exp-cross-build.yml
@@ -281,7 +281,12 @@ jobs:
           echo "Downloading latest syntaxflow rule info..."
           wget -O syntaxflow-meta.json https://aliyun-oss.yaklang.com/yak/latest/syntaxflow-meta.json
           if [ $? -ne 0 ]; then
-            echo "::error::Failed to download syntaxflow meta info"
+            echo "::error::Failed to download syntaxflow meta info, empty file will create it "
+          fi
+          
+          wget -O summary-syntaxflow-meta.yak  https://aliyun-oss.yaklang.com/syntaxflow/summary-syntaxflow-meta.yak
+          if [ $? -ne 0 ]; then
+            echo "::error::Failed to download syntaxflow meta info generator"
             exit 1
           fi
           
@@ -289,7 +294,7 @@ jobs:
           ls -l  | grep syntaxflow
           
           echo "Generating meta info with yak script..."
-          ./yak_linux_amd64 scripts/syntaxflow_meta_info.yak \
+          ./yak_linux_amd64 ./summary-syntaxflow-meta.yak \
             --output syntaxflow-meta.json \
             --version ${{ env.YAK_TAG }} \
             --custom-ai \
