fix crossbuild ci

diff --git a/.github/workflows/exp-cross-build.yml b/.github/workflows/exp-cross-build.yml
--- a/.github/workflows/exp-cross-build.yml
+++ b/.github/workflows/exp-cross-build.yml
@@ -10,7 +10,30 @@ on:
       - '.github/workflows/exp-cross-build.yml'
 
 jobs:
+  check_commit_msg:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Check Commit Message
+        run: |
+          git fetch --all
+          echo "generate commit messages ... "
+          ./scripts/generate-commit.sh > /tmp/raw_commit_message.txt
+          cat /tmp/raw_commit_message.txt
+          echo "-------------"
+          # 检查 /tmp/raw_commit_message.txt 文件是否存在
+          if [ ! -f /tmp/raw_commit_message.txt ]; then
+            echo "Error: /tmp/raw_commit_message.txt does not exist."
+            exit 1
+          fi
+            - name: Upload sha256 checksums artifacts
+      - uses: actions/upload-artifact@v4
+        with:
+          name: raw_commit_message.txt
+          path: /tmp/raw_commit_message.txt
+
   build_and_upload_to_oss:
+    needs: check_commit_msg
     strategy:
       matrix:
         os:
@@ -159,11 +182,10 @@ jobs:
           echo "generate commit messages ... "
           ./scripts/generate-commit.sh > /tmp/raw_commit_message.txt
           cat /tmp/raw_commit_message.txt
+          echo "-------------"
+          cat /tmp/msg.txt
           
           ./yak_linux_amd64 ./scripts/output_release_info.yak --ai-type openai --apikey ${{ secrets.OPENAI_APIKEY }} --filename /tmp/raw_commit_message.txt --ai-model gpt-4-0613
-          
-          echo "start to check release txt"
-          ls | grep release
           
           echo "start to handle versions"
           if [ -f current_version.txt ]; then rm current_version.txt; fi
